/** @deprecated Import from ./settings.js — kept for backward compatibility. */
export {
  getServiceUrl,
  getProvider,
  getModel,
  getWorkspaceRoot,
  getClientSettings,
  getApiKey,
  getDefaultChatMode,
  isTabAutocompleteEnabled,
  getTabDebounceMs,
  isIncludeActiveFile,
  isIncludeOpenFiles,
  getMaxFileContextChars,
  isAutoApproveTerminal,
  isAutoApproveFileWrites,
  isYoloMode,
  isAutoIndexOnSave,
  isAutoIndexOnOpen,
  isPrivacyMode,
  getTabModel,
  getInlineModel,
  getBaseUrl,
  isMcpEnabled,
  getMaxContextAttachments,
} from './settings';
